version: '3'

services:
  j2me-emulator:
    build: .
    volumes:
      - ./games:/app/games
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0.0}
    network_mode: host
    platform: linux/amd64